### ISSUE TITLE
Pre-launch feedback

### ISSUE THREAD

**Issue by tomakehurst** [mwinteringham/wiremock-chrome-extension#3]
I thought this would be a better feedback medium than Twitter DMs.

Here are my thoughts after a quick play with the plugin:

* When editing a mapping, not all the fields of the form are populated with the existing values.
* The path/regex/partial dropdown is a bit confusing - not sure what partial means and how it maps onto WM's underlying URL matching options.
* In the mappings list view, longer URLs overlap with the status code.
* Priority field has no label when populated and being a simple integer it's not necessarily obvious what it is
* I can't set the predicate for the request body. Not clear by what method it would attempt to match, and it's definitely useful to have control over this.
* I can only specify one request body parameter, whereas WireMock permits many. This can be useful if you're matching on e.g. a set of JSONPath expressions targeting different bits of the payload
* Doesn't support matching on cookies (other than by matching the header)
* Doesn't provide a way for me to configure proxy or fault mappings (maybe you consider this too much for now?).
* Might be a nice idea to support the new (admittedly as yet undocumented) name field on stub mappings.
* When setting the host it might be useful to be able to set the protocol, for cases where folks have deployed it behind HTTPS termination.
* Would be nice to be able to view the request journal.

**Comment by mwinteringham** [comment]
Thanks for @tomakehurst I will probably have question to follow this up but I will get working on this feedback.

**Comment by mwinteringham** [comment]
@tomakehurst I have been trying to reproduce the issue of not all the fields of the form are populated with the existing values.  Can you shed some more light onto what fields specifically are causing a problem?

**Comment by tomakehurst** [comment]
For me the only fields that get preserved seem to be URL, URL match type and method.
<img width="488" alt="screen shot 2017-01-31 at 18 56 12" src="https://cloud.githubusercontent.com/assets/707169/22479800/079cdcea-e7e7-11e6-8ef1-d8ed319eea58.png">
<img width="487" alt="screen shot 2017-01-31 at 18 56 03" src="https://cloud.githubusercontent.com/assets/707169/22479799/079825b0-e7e7-11e6-950a-6d75dc4e25ff.png">

**Comment by mwinteringham** [comment]
Hi @tomakehurst I've made some progress on the issues you've risen but I have a few more questions to ask you:

**Would be nice to be able to view the request journal**
I'm not entirely sure what the request journal is and how I access it.  I've looked at the Docs but I'm struggling to understand how to access it and use it.

**I can't set the predicate for the request body. Not clear by what method it would attempt to match, and it's definitely useful to have control over this.**
Again I'm not sure what you mean by setting the predicate, can you give me more details? I am updating the extension to take multiple matching request payloads, is this related to predicates for request bodies?

**Comment by mwinteringham** [comment]
Done a bit more research on the predicates for requests and I now understand what you mean.  I have been calling them keys since I have used the JSON mappings to inform requirements.

Currently, the predicate/key is decided under the hood by doing a lookup on the first character of the request body.  I have made an assumption that how each request is started is unique to the type of predicate/key you want to use.

```
switch (requestPayload[i].charAt(0)) {
      case '{':
          payload.request.bodyPatterns.push({
            "equalToJson": requestPayload[i]
          });
          break;
        case '$':
          payload.request.bodyPatterns.push({
            "matchesJsonPath": requestPayload[i]
          });
          break;
        case '<':
          payload.request.bodyPatterns.push({
            "equalToXml": requestPayload[i]
          });
          break;
        case '/':
          payload.request.bodyPatterns.push({
            "matchesXPath": requestPayload[i]
          });
          break;
      }
```

I think this could be improved by giving some feedback on what the extension has assumed the request body predicate/key to be.

**Comment by mwinteringham** [comment]
I have gone over the list and fixed bugs, implemented some of the suggestions and hived off other features in #4 #5 #6 #7

**Comment by tomakehurst** [comment]
Sorry for the delayed reply. The request journal is just the log of received requests, accessible via `/__admin/requests`
