### ISSUE TITLE
Cannot scroll in mappings view

### ISSUE THREAD

**Issue by mrk-han** [mwinteringham/wiremock-chrome-extension#9]
Unable to scroll when there are enough mappings in the extension to be scrollable

**Comment by mwinteringham** [comment]
HI @mrk-han any chance of a screenshot to see the behaviour?

**Comment by mrk-han** [comment]
![image](https://user-images.githubusercontent.com/22263679/47452972-810ed080-d799-11e8-8f47-4b11858f4207.png)

**Comment by mrk-han** [comment]
When editing the mapping, cannot scroll in this view. Can exit out of request payloads to see more, but still cannot scroll. I know this tool isn't under active development, but I was wondering if you'd witnessed the same. Experimenting to see if this tool can help our QA adjust to Wiremock more easily.

**Comment by mwinteringham** [comment]
Tbh @mrk-han the UI is a bit of a mess and could do with an overhaul. I think this is encouraging me to do the necessary work to clean it up :)

**Comment by mwinteringham** [comment]
Hi @mrk-han not to sound like a cliche but it works fine on my machine. Could you give me some details on the browser you are using and what OS?

**Comment by mrk-han** [comment]
@mwinteringham 

The most peculiar thing... it's working perfectly for me now, too. Since I posted this, I updated Chrome and Updated to Mojave... but also it could have been one of my other extensions hecking something up. I'm just glad it's working.

Sorry for the swirl!

**Comment by mwinteringham** [comment]
Haha spooky. I have done similar which may have resolved it. Will close this and keep and eye on the issue.
